services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
      - ./migrations:/code/migrations
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:8
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
